on:
  pull_request:
    branches:
      - main

jobs:
  check_compile:
    runs-on: ubuntu-latest
    name: Check TeX Compilation
    steps:
      - uses: actions/checkout@v6

      - name: GitHub Action for LaTeX
        uses: xu-cheng/latex-action@25080975331dc4fc8e6f1af55788e00f84f51fff  # v4.0.0
        with:
          root_file: main.tex
          latexmk_use_lualatex: true
