on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  compile_and_release:
    runs-on: ubuntu-latest
    name: Compile TeX to PDF and Release
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6

      - name: GitHub Action for LaTeX
        uses: xu-cheng/latex-action@25080975331dc4fc8e6f1af55788e00f84f51fff  # v4.0.0
        with:
          root_file: main.tex
          latexmk_use_lualatex: true

      - name: Delete existing "latest" release and tag (if present)
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release delete latest --repo ${{ github.repository }} --yes --cleanup-tag || true

      - name: Create "latest" Release
        uses: softprops/action-gh-release@153bb8e04406b158c6c84fc1615b65b24149a1fe  # v2.6.1
        with:
          tag_name: latest
          name: Latest Build
          body: |
            Compiled PDF ${{ github.sha }}
          draft: false
          prerelease: false
          files: main.pdf
